version: '3.8'

services:
  postgres:
    image: postgres:latest  # Usando a versão mais recente do PostgreSQL
    container_name: postgres_container  # Nome do contêiner
    environment:
      - POSTGRES_USER=admin      # Usuário do PostgreSQL
      - POSTGRES_PASSWORD=admin  # Senha do PostgreSQL
      - POSTGRES_DB=ExpenseTrackerApi  # Nome do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    ports:
      - "5432:5432"  # Expondo a porta 5432 para o host
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
